# SpiNNaker Nengo Integration
# Ensemble Component
# ----------------------------------------------------------------------------
# Authors:
#  Andrew Mundy <mundya@cs.man.ac.uk>
#  Terry Stewart
#
# February 2014
# ----------------------------------------------------------------------------

APP = nengo_ensemble
SOURCES = ensemble_main.c ensemble_data.c ensemble_harness.c ensemble_output.c ensemble_update.c ensemble_pes.c ensemble_voja.c ensemble_filtered_activity.c record_spikes.c record_learnt_encoders.c ../common/input_filter.c
include ../Makefile.depend
